name: 'outra.s'
keywords: 'health, wellbeing, well-being, lifestyle, life-style'
description: 'Much more than just antennas'

url: https://outras.ml
baseurl: ''
port: 45666
permalink: /blog/:title/

collections:
  relative-intensity:
    title: "Relative Intensity Collection"
    output: true
    permalink: /:collection/:title/
  visualizing-worlds:
    title: "Visualizing Worlds Collection"
    output: true
    permalink: /:collection/:title/
  divination:
    title: "Divination"
    output: true
    permalink: /:collection/:title/
  algotypes:
    title: "Algotypes"
    output: true
    permalink: /:collection/:title/

social:
  tumblr: ""
  pinterest: ""
  instagram: "https://www.instagram.com/algotypes/"
  twitter: ""
  facebook: ""
  youtube-play: "https://www.youtube.com/channel/UCpjDzZMzbi8PpqhclAOs_iA"
  vimeo: ""
  github: ""
  soundcloud: ""
  envelope: "mailto:algotypes@gmail.com"
twitter_user: ""

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "list"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "cursos"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "projetos"
    values:
      layout: "product"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md]
